baseURL: "https://gifted-gates-4b6df9.netlify.app/"
languageCode: "en-us"
title: "Rohan Patankar | Portfolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"
  
enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: /images/fav.png
  description: "Rohan's personal portfolio"

  # Navbar Menus
  

  # home
  disable_home: false
  profile_image: /images/profile.png
  name: "Rohan Patankar"
  namecolor: ffc107
  profession: "Aspiring Data Scientist"
  github: "https://github.com/ROHANPATAKAR/"
  linkedin: "https://www.linkedin.com/in/rohan-patankar-2aa707213/"
  twitter: "https://twitter.com/Rohan20075428"
  gmail: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=rohanpatankar926@gmail.com"
  instagram: "https://instagram.com/__rohan__95?utm_medium=copy_link"
  

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=rohanpatankar926@gmail.com"
      fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=rohanpatankar926@gmail.com"

  # About
  disable_about: false  
  descripe_l1_person: "Hii there! Myself **Rohan** and I am persuing my B.Tech in **DataScience** at **Jain University** having CGPA of **8.88**. I am very passionate about evergrowing technology especially in the field of DataScience and Web Devolopment."
  descripe_l2_person: "### Real world capabilities"
  descripe_l3_person: "I believe Skills are the ability to perform certain tasks well. Some skills can be measured and you acquire them through deliberate effort, others are related to your personality traits. In other words, not all skills are created equal. That’s why we call some of them “hard” and others “soft”.**Hard skills** are the skills that I’ve acquired through deliberate effort. They can be learned, taught, and measured.My hard skills include: **HTML, CSS, Python, SQL, JavaScript, MachineLearning, C and others.**
  **Soft skills**, on the other hand, are closely tied to one’s personality traits. Some of my softskills are **leadership, communication, or other interpersonal skills**. As opposed to hard skills, soft skills cannot be easily taught. Examples of soft skills include: problem-solving, negotiating, multitasking, time management, presenting, and others."
  descripe_l4_person: "*You can find my works [here](#projects)* "

  skills:
    - name: "Python"
      percentage: 80
    - name: C
      percentage: 75
    - name: "HTML"
      percentage: 90
    - name: "CSS"
      percentage: 75
    - name: JavaScript
      percentage: 70
    - name: Machine Learning
      percentage: 80
    - name: Tableu
      percentage: 80
    - name: SQL
      percentage: 80
    - name: Mongodb
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "PantechSolutions"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Machine Learning Internship"
      startdate: "Sep 2021"
      enddate: "Oct 2021"
      featuredpoints:
        - point: "Learnt all types of supervised and unsupervised algorithms"
        - point: "Learnt to build neural networks using ann,cnn,rnn,LSTM etc"
        - point: "build various types of projects using different ML and DL algorithms"
    - company: "AzureSkynets_Pvt-Ltd"
      # id: "AzureSkynets Pvt Ltd" // use this, when you want to change the id(used for navigation)
      role: "Python Programming Internship"
      startdate: Jan 2020
      enddate: Feb 2020
      featuredpoints:
        - point: "Learnt python programming from datatypes to classes,objects,OOPS"
        - point: "Learnt libraries like numpy,pandas,matplotlib,seaborn,plotly."
        - point: "Built projects like ML-preprocessor with CLI,Email Slicer and so on"

  # Education
  disable_education: false
  education:
    - degree: "B.tech-"
      branch: "DataScience(HONOURS)"
      university: "Jain University"
     
      startedyear: "2019"
      graduation: "2023"
    - degree: "Class XII-"
      branch: "PCMS"
      university: "Vidyodaya PU College"
      startedyear: "2018"
      graduation: "2019"
    - degree: "Class X"
      university: "Indrali English Medium High School"
      startedyear: "2017"
      graduation: "2018"

  # Projects
  disable_projects: false
  projects:
    - name: "progress"
      img: /images/progress.jpg
      githublink: "https://github.com/ROHANPATAKAR/ml-preprocessor-cli"
      featuredlink: ""
      description: "Description of project"
    - name: "ML Preprocessor CLI"
      img: /images/ml_pic.png
      githublink: "https://github.com/ROHANPATAKAR"
      featuredlink: "https://www.crio.do/projects/python-preprocessor-cli/"
      description: "> The main objective of this project is You will implement a Command Line Interface (CLI) which will preprocess your dataset and save your time."

  # services
  disable_achievements: false
  achievements:
    - title: "Website Devolopment"
      description: "Design a website for personal use or for business purpose using HTML, CSS, JS and Python."
      img: /images/Website-Design-new.jpg
    - title: Data Analysis
      description: "With the help of tableu or python analyze the data of client needs which help them to solve business problems."
      img: /images/da.jpg
      # url: https://example.com
    - title: App Devolopment Soon...
      description: 
      img: /images/app.jpg
    
  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you! 
  email: "rohanpatankar926@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
